Remove DEV_MODE feature because it is no longer used by IDEs.

diff --git a/6.0/build/s2i/bin/assemble b/6.0/build/s2i/bin/assemble
--- a/6.0/build/s2i/bin/assemble
+++ b/6.0/build/s2i/bin/assemble
@@ -21,77 +21,73 @@ if [ -d /tmp/src ]; then
   mv /tmp/src/* ./
 fi
 
-if [ "$DEV_MODE" == true ]; then
-  BUILD_TYPE=source
-else
-  if [ -n "${DOTNET_STARTUP_PROJECT}" -a -n "${DOTNET_STARTUP_ASSEMBLY}" ]; then
-    echo "error: DOTNET_STARTUP_PROJECT and DOTNET_STARTUP_ASSEMBLY are both set"
-    echo "Use DOTNET_STARTUP_PROJECT for source builds or DOTNET_STARTUP_ASSEMBLY for pre-built applications."
+if [ -n "${DOTNET_STARTUP_PROJECT}" -a -n "${DOTNET_STARTUP_ASSEMBLY}" ]; then
+  echo "error: DOTNET_STARTUP_PROJECT and DOTNET_STARTUP_ASSEMBLY are both set"
+  echo "Use DOTNET_STARTUP_PROJECT for source builds or DOTNET_STARTUP_ASSEMBLY for pre-built applications."
+  exit 1
+fi
+
+# determine candidate source projects (PROJFILES) or pre-built entrypoint assembly (DOTNET_STARTUP_ASSEMBLY)
+if [ -n "${DOTNET_STARTUP_ASSEMBLY}" ]; then
+  # binary build
+  if [ ! -f "${DOTNET_STARTUP_ASSEMBLY}" ]; then
+    echo "error: Source does not contain DOTNET_STARTUP_ASSEMBLY: ${DOTNET_STARTUP_ASSEMBLY}"
     exit 1
   fi
-
-  # determine candidate source projects (PROJFILES) or pre-built entrypoint assembly (DOTNET_STARTUP_ASSEMBLY)
-  if [ -n "${DOTNET_STARTUP_ASSEMBLY}" ]; then
-    # binary build
-    if [ ! -f "${DOTNET_STARTUP_ASSEMBLY}" ]; then
-      echo "error: Source does not contain DOTNET_STARTUP_ASSEMBLY: ${DOTNET_STARTUP_ASSEMBLY}"
+else
+  # source build
+  PROJFILES=(`find "${DOTNET_STARTUP_PROJECT:-.}" -maxdepth 1 -name "*.??proj"`)
+  # If we didn't find a project file, see if we can do a binary build instead.
+  if [ -z "${DOTNET_STARTUP_ASSEMBLY}" -a ${#PROJFILES[@]} -eq 0 ]; then
+    # determine entrypoint assembly based on *.runtimeconfig.json files
+    RUNTIMECFGFILES=(`find -maxdepth 1 -name "*.runtimeconfig.json"`)
+    if [ ${#RUNTIMECFGFILES[@]} -eq 1 ]; then
+      DOTNET_STARTUP_ASSEMBLY="${RUNTIMECFGFILES[0]: : -19}.dll"
+    elif [ ${#RUNTIMECFGFILES[@]} -gt 1 ]; then
+      echo "error: Repository contains multiple startup assemblies"
+      echo "You can select the startup assembly by specifying DOTNET_STARTUP_ASSEMBLY."
       exit 1
-    fi
-  else
-    # source build
-    PROJFILES=(`find "${DOTNET_STARTUP_PROJECT:-.}" -maxdepth 1 -name "*.??proj"`)
-    # If we didn't find a project file, see if we can do a binary build instead.
-    if [ -z "${DOTNET_STARTUP_ASSEMBLY}" -a ${#PROJFILES[@]} -eq 0 ]; then
-      # determine entrypoint assembly based on *.runtimeconfig.json files
-      RUNTIMECFGFILES=(`find -maxdepth 1 -name "*.runtimeconfig.json"`)
-      if [ ${#RUNTIMECFGFILES[@]} -eq 1 ]; then
-        DOTNET_STARTUP_ASSEMBLY="${RUNTIMECFGFILES[0]: : -19}.dll"
-      elif [ ${#RUNTIMECFGFILES[@]} -gt 1 ]; then
-        echo "error: Repository contains multiple startup assemblies"
-        echo "You can select the startup assembly by specifying DOTNET_STARTUP_ASSEMBLY."
-        exit 1
-      fi
     fi
   fi
+fi
 
-  if [ -n "${DOTNET_STARTUP_ASSEMBLY}" ]; then
-    # binary build
-    BUILD_TYPE=binary
-    APP_DLL_NAME="${DOTNET_STARTUP_ASSEMBLY}"
-    echo "Using pre-built application with entrypoint assembly: ${DOTNET_STARTUP_ASSEMBLY}"
-  else
-    # source build
-    BUILD_TYPE=source
-    if [ ${#PROJFILES[@]} -eq 1 ]; then
-      # single project file
-      DOTNET_STARTUP_PROJECT="${DOTNET_STARTUP_PROJECT:-.}"
-      if [ -n "$DOTNET_ASSEMBLY_NAME" ]; then
-        APP_DLL_NAME="${DOTNET_ASSEMBLY_NAME}.dll"
-      else
-        PROJFILE=$(basename ${PROJFILES[0]})
-        APP_DLL_NAME="${PROJFILE: : -7}.dll"
-      fi
+if [ -n "${DOTNET_STARTUP_ASSEMBLY}" ]; then
+  # binary build
+  BUILD_TYPE=binary
+  APP_DLL_NAME="${DOTNET_STARTUP_ASSEMBLY}"
+  echo "Using pre-built application with entrypoint assembly: ${DOTNET_STARTUP_ASSEMBLY}"
+else
+  # source build
+  BUILD_TYPE=source
+  if [ ${#PROJFILES[@]} -eq 1 ]; then
+    # single project file
+    DOTNET_STARTUP_PROJECT="${DOTNET_STARTUP_PROJECT:-.}"
+    if [ -n "$DOTNET_ASSEMBLY_NAME" ]; then
+      APP_DLL_NAME="${DOTNET_ASSEMBLY_NAME}.dll"
     else
-      # zero or more than 1 project files -> fail
-      if [ ${#PROJFILES[@]} -eq 0 ]; then
-        echo "error: DOTNET_STARTUP_PROJECT has no project file"
-      else
-        echo "error: DOTNET_STARTUP_PROJECT contains multiple project files"
-      fi
-      echo "You can specify the startup project by adding an '.s2i/environment' file to the source repository."
-      # find all projects and strip leading './'
-      PROJFILES=(`find -name "*.??proj" | sed "s|^\./||" | sort`)
-      if [ ${#PROJFILES[@]} -eq 0 ]; then
-        echo "The source repository has no project files."
-      else
-        echo "The source repository contains the following projects:"
-        for PROJFILE in ${PROJFILES[@]}; do
-          echo "- ${PROJFILE}"
-        done
-        echo "Update the '.s2i/environment' file to specify the project you want to publish, for example DOTNET_STARTUP_PROJECT=${PROJFILES[0]}".
-      fi
-      exit 1
+      PROJFILE=$(basename ${PROJFILES[0]})
+      APP_DLL_NAME="${PROJFILE: : -7}.dll"
     fi
+  else
+    # zero or more than 1 project files -> fail
+    if [ ${#PROJFILES[@]} -eq 0 ]; then
+      echo "error: DOTNET_STARTUP_PROJECT has no project file"
+    else
+      echo "error: DOTNET_STARTUP_PROJECT contains multiple project files"
+    fi
+    echo "You can specify the startup project by adding an '.s2i/environment' file to the source repository."
+    # find all projects and strip leading './'
+    PROJFILES=(`find -name "*.??proj" | sed "s|^\./||" | sort`)
+    if [ ${#PROJFILES[@]} -eq 0 ]; then
+      echo "The source repository has no project files."
+    else
+      echo "The source repository contains the following projects:"
+      for PROJFILE in ${PROJFILES[@]}; do
+        echo "- ${PROJFILE}"
+      done
+      echo "Update the '.s2i/environment' file to specify the project you want to publish, for example DOTNET_STARTUP_PROJECT=${PROJFILES[0]}".
+    fi
+    exit 1
   fi
 fi
 
@@ -174,13 +170,6 @@ EOF
       dotnet tool install -g $VERBOSITY_OPTION $TOOL_RESTORE_OPTIONS $DOTNET_TOOL_VERSION_OPTION $DOTNET_TOOL_NAME
     done
   fi
-fi
-
-if [ "$DEV_MODE" == true ]; then
-  # fix permissions
-  fix-permissions /opt/app-root
-
-  exit 0
 fi
 
 if [ "$BUILD_TYPE" == "source" ]; then
