Add DOTNET_ASSEMBLY_NAME envvar (#42)
It is used to select the assembly to run. This must NOT include the .dll
extension. Set this to the output assembly name specified in project.json
(specified via buildOptions/outputName or name) .

For project.json, the assembly name defaults to project.json's parent
folder if none of the above properties are specified.
The parent folder is used as the default value for DOTNET_ASSEMBLY_NAME.
When project.json is at the context directory, the parent folder name will
be 'src'. So, by default, this generates a 'src.dll' assembly. Setting
DOTNET_ASSEMBLY_NAME will cause the project to be built in a folder
named $DOTNET_ASSEMBLY_NAME which builds a $DOTNET_ASSEMBLY_NAME.dll.

Also note that sources in the built container will be in subfolder
$DOTNET_ASSEMBLY_NAME rather than in the current working directory
directly.

diff --git a/1.1/s2i/bin/assemble b/1.1/s2i/bin/assemble
--- a/1.1/s2i/bin/assemble
+++ b/1.1/s2i/bin/assemble
@@ -18,8 +18,21 @@ if [ -n "${DOTNET_NPM_TOOLS}" ]; then
   popd
 fi
 
+# project.json defaults to naming the assembly the same as the folder
+if [ -n "$DOTNET_ASSEMBLY_NAME" ]; then
+  mkdir "$DOTNET_ASSEMBLY_NAME"
+  cd "$DOTNET_ASSEMBLY_NAME"
+fi
+
 echo "---> Copying application source ..."
 cp -Rf /tmp/src/. ./
+
+# output assembly name
+if [ -n "$DOTNET_ASSEMBLY_NAME" ]; then
+  APP_DLL_NAME="${DOTNET_ASSEMBLY_NAME}.dll"
+else
+  APP_DLL_NAME="$(basename "$(realpath "${DOTNET_STARTUP_PROJECT}")").dll"
+fi
 
 echo "---> Installing dependencies ..."
 dotnet restore $DOTNET_RESTORE_ROOT
@@ -40,8 +53,13 @@ done
 
 rm -rf $DOTNET_REFERENCE_ASSEMBLIES_PATH
 
+# check if the assembly used by the script exists
+if [ ! -f "$DOTNET_PUBLISH_PATH/${APP_DLL_NAME}" ]; then
+  echo "error: Build output does not contain entrypoint assembly: ${APP_DLL_NAME}"
+  exit 1
+fi
+
 # Create run script in publish folder
-APP_DLL_NAME="$(basename "$(realpath "${DOTNET_STARTUP_PROJECT}")").dll"
 cat << EOF >"$DOTNET_RUN_SCRIPT"
 #!/bin/bash
 exec dotnet ${APP_DLL_NAME} \$@
