2.1: Add DOTNET_SSL_DIRS
Used to specify a list of folders with additional certificates to trust. The certificates are
trusted by each process that runs during the build and all processes that runs in the image
after the build (including the application that was built). The folders can be absolute paths
(starting with `/`) or paths in the source repository (e.g. `certificates`).

diff --git a/2.1/build/test/run b/2.1/build/test/run
--- a/2.1/build/test/run
+++ b/2.1/build/test/run
@@ -30,13 +30,14 @@ OPENSHIFT_ONLY=${OPENSHIFT_ONLY:-false}
 test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
 source ${test_dir}/testcommon
 
-sdk_default_version="2.1.300"
 if [ "$BUILD_CENTOS" = "true" ]; then
+sdk_default_version="2.1.300"
 sdk_latest_version="2.1.300"
 sdk_versions=( "2.1.300" )
 else
-sdk_latest_version="2.1.300"
-sdk_versions=( "2.1.300" )
+sdk_default_version="2.1.301"
+sdk_latest_version="2.1.301"
+sdk_versions=( "2.1.301" )
 fi
 
 sample_app_url="https://github.com/redhat-developer/s2i-dotnetcore-ex.git"
@@ -49,17 +50,19 @@ s2i_image_tag() {
 s2i_build_output_log() {
   local app="$1"
   local tag="$2"
+  shift 2
 
   docker_rmi ${tag}
-  s2i build --pull-policy=never -e DOTNET_SDK_VERSION=$sdk_version "file://${test_dir}/${app}" ${IMAGE_NAME} ${tag} 2>&1
+  s2i build --pull-policy=never -e DOTNET_SDK_VERSION=$sdk_version "$@" "file://${test_dir}/${app}" ${IMAGE_NAME} ${tag} 2>&1
 }
 
 s2i_build() {
   local app="$1"
   local tag=$(s2i_image_tag ${app})
+  shift 1
 
   local output;
-  output=$(s2i_build_output_log ${app} ${tag})
+  output=$(s2i_build_output_log ${app} ${tag} "$@")
   if [ $? -ne 0 ]; then
     error "$output"
     echo "no-image"
@@ -530,6 +533,42 @@ test_devmode() {
   test_devmode_change
 }
 
+docker_run_certificatecount()
+{
+  local app=certificatecount
+
+  # build image
+  local image=$(s2i_build ${app} "$@")
+  local output=$(docker_run ${image})
+  # cleanup
+  docker_rmi ${image}
+
+  echo $output | awk '{print $NF}'
+}
+
+test_certificates() {
+  test_start
+
+  local default_count=$(docker_run_certificatecount)
+  # It is unlikely to have less than 100 certificates.
+  if [ "$default_count" -lt 100 ]; then
+    error "Default number of certificates is too low: '${default_count}'"
+    exit 1
+  fi
+
+  # DOTNET_SSL_DIRS=/doesntexist
+  # We add a non existing directory, which must be ingored.
+  local default_count_with_nonexist=$(docker_run_certificatecount -e DOTNET_SSL_DIRS=/doesntexist)
+  assert_equal "$default_count" "$default_count_with_nonexist"
+
+  # DOTNET_SSL_DIRS=/doesntexist certdir1 certdir2
+  # - /doesntexist : ignored
+  # - certdir1     : contains 1 certificate in 1 file
+  # - certdir2     : contains 2 certificates in 1 file
+  local count_with_additional=$(docker_run_certificatecount -e DOTNET_SSL_DIRS='/doesntexist certdir1 certdir2')
+  assert_equal "$count_with_additional" "$(($default_count + 3))"
+}
+
 info "Testing ${IMAGE_NAME}"
 
 if [ ${OPENSHIFT_ONLY} != true ]; then
@@ -550,6 +589,7 @@ if [ ${OPENSHIFT_ONLY} != true ]; then
     test_split_build
     test_new_web_app
     test_user
+    test_certificates
   done
   # when unset, default to the lowest sdk version
   info "default sdk(${sdk_default_version}):"
