Add STOP_ON_ERROR flag for choosing to stop or continue when a test fails.

diff --git a/2.1/build/test/run b/2.1/build/test/run
--- a/2.1/build/test/run
+++ b/2.1/build/test/run
@@ -16,7 +16,13 @@
 # DEBUG environment variable, if not empty, makes 'run' to log every step
 # of testing.
 #
+# STOP_ON_ERROR determines if the tests should exit on encountering
+# the first error, or keep going and list all failed tests at the end.
+# Defaults to 'true', can be set to 'false'
+#
 # Example usage: $ sudo ./test/run
+
+STOP_ON_ERROR=${STOP_ON_ERROR:-true}
 
 if [ "$IMAGE_OS" = "CENTOS" ]; then
   IMAGE_NAME=${IMAGE_NAME:-dotnet/dotnet-21-centos7}
@@ -719,6 +725,17 @@ if [ ${OPENSHIFT_ONLY} != true ]; then
   test_incremental_without_packages
 else
   test_imagestream_sample
+fi
+
+if [ "$STOP_ON_ERROR" != "true" ]; then
+  failures=(${TEST_FAILURES})
+  if [ ${#failures[@]} -gt 0 ]; then
+    echo "[ERROR] Tests failed: ${#failures[@]}"
+    for item in ${failures[@]}; do
+      echo "  ${item}"
+    done
+    exit 1
+  fi
 fi
 
 info "All tests finished successfully."
