1.x: Use HTTP_PROXY in .NET Core

diff --git a/1.0/test/run b/1.0/test/run
--- a/1.0/test/run
+++ b/1.0/test/run
@@ -434,6 +434,24 @@ test_new_web_app() {
   cleanup ${app}
 }
 
+test_http_proxy() {
+  info "Testing http_proxy ..."
+
+  # When HTTP_PROXY is set, we set http_proxy to match (unless it's already set).
+  local expected="proxy0"
+  local out=$(docker run --rm -e HTTP_PROXY=proxy0 ${IMAGE_NAME} bash -c 'echo $http_proxy')
+  if ! echo "${out}" | grep -q "${expected}"; then
+    echo "ERROR[http_proxy] Expected '${expected}', got '${out}'"
+    exit 1
+  fi
+  expected="proxy1"
+  out=$(docker run --rm -e HTTP_PROXY=proxy0 -e http_proxy=proxy1 ${IMAGE_NAME} bash -c 'echo $http_proxy')
+  if ! echo "${out}" | grep -q "${expected}"; then
+    echo "ERROR[http_proxy] Expected '${expected}', got '${out}'"
+    exit 1
+  fi
+}
+
 info "Testing ${IMAGE_NAME}"
 
 # Since we built the candidate image locally, we don't want S2I attempt to pull
@@ -447,6 +465,8 @@ check_result $?
 # Verify the 'usage' script is working properly when running the base image with 'docker run ...'
 test_docker_run_usage "${sample_app_url}"
 check_result $?
+
+test_http_proxy
 
 # Verify OpenShift's s2i-dotnetcore-ex runs
 if [ ${OPENSHIFT_ONLY} = true ]; then
