Create runtime and build images.
Existing files moved from <ver>/<stuff> to <ver>/build/<stuff>.
Files for building runtime images can be found at <ver>/runtime/<stuff>.
Test files are still located at <var>/test.

diff --git a/2.0/test/run b/2.0/test/run
--- a/2.0/test/run
+++ b/2.0/test/run
@@ -15,6 +15,7 @@
 # Example usage: $ sudo ./test/run
 
 IMAGE_NAME=${IMAGE_NAME:-dotnet/dotnet-20-rhel7}
+RUNTIME_IMAGE_NAME=${RUNTIME_IMAGE_NAME:-${IMAGE_NAME}-runtime}
 
 OPENSHIFT_ONLY=${OPENSHIFT_ONLY:-false}
 
@@ -47,6 +48,7 @@ image_exists() {
 }
 
 container_exists() {
+  local cid_file="$1"
   image_exists $(cat $cid_file)
 }
 
@@ -80,18 +82,23 @@ prepare() {
 }
 
 run_test_application() {
-  docker run --user=100001 ${CONTAINER_ARGS} -d --cidfile=${cid_file} -p ${test_port}:${test_port} ${IMAGE_NAME}-testapp
+  local image="$1"
+  local cid_file="$2"
+  docker run --user=100001 ${CONTAINER_ARGS} -d --cidfile=${cid_file} -p ${test_port}:${test_port} ${image}
 }
 
 run_cli_test_application() {
-  docker run --user=100001 ${CONTAINER_ARGS} -i --rm ${IMAGE_NAME}-testapp
+  local image=$1
+  docker run --user=100001 ${CONTAINER_ARGS} -i --rm ${image}
 }
 
-cleanup_app() {
+cleanup_container() {
+  local cid_file="$1"
   info "Cleaning up app container ..."
   if [ -f $cid_file ]; then
-    if container_exists; then
+    if container_exists "${cid_file}"; then
       docker stop $(cat $cid_file)
+      docker rm  $(cat $cid_file)
     fi
   fi
 }
@@ -100,6 +107,9 @@ cleanup() {
   info "Cleaning up the test application image"
   if image_exists ${IMAGE_NAME}-testapp; then
     docker rmi -f ${IMAGE_NAME}-testapp
+  fi
+  if image_exists ${RUNTIME_IMAGE_NAME}-testapp; then
+    docker rmi -f ${RUNTIME_IMAGE_NAME}-testapp
   fi
   rm -rf ${test_dir}/${1}/.git
 }
@@ -159,7 +169,7 @@ test_pid_1() {
   out="$(docker exec $(cat ${cid_file}) /bin/bash -c 'ps --no-headers -o args 1' 2>&1)"
   if ! echo "${out}" | grep "dotnet" | grep -q '\.dll' ; then
     echo "'dotnet <assembly>' not process with PID 1. PID 1 process was: '${out}'"
-    cleanup_app
+    cleanup_container "${cid_file}"
     return 1
   fi
 }
@@ -168,9 +178,10 @@ test_scl_usage() {
   local run_cmd="$1"
   local expected="$2"
   local cid_file="$3"
+  local image="$4"
 
-  info "Testing the image SCL enable"
-  out=$(docker run --rm ${IMAGE_NAME} /bin/bash -c "${run_cmd}" 2>&1)
+  info "Testing the image SCL enable for '${run_cmd}'"
+  out=$(docker run --rm ${image} /bin/bash -c "${run_cmd}" 2>&1)
   if ! echo "${out}" | grep -q "${expected}"; then
     echo "ERROR[/bin/bash -c "${run_cmd}"] Expected '${expected}', got '${out}'"
     return 1
@@ -233,52 +244,103 @@ test_http() {
   return $result
 }
 
-test_web_application() {
-  local cid_file=$(mktemp -u --suffix=.cid)
-  # Verify that the HTTP connection can be established to test application container
-  run_test_application &
-
-  # Wait for the container to write it's CID file
-  wait_for_cid
-
-  test_scl_usage "dotnet --version" "${dotnet_version}" "${cid_file}"
-  check_result $?
-
-  # Verify $HOME != $CWD. See https://github.com/redhat-developer/s2i-dotnetcore/issues/28
-  test_scl_usage "pwd" "/opt/app-root/src" "${cid_file}"
-  check_result $?
-  test_scl_usage "echo \$HOME" "/opt/app-root" "${cid_file}"
-  check_result $?
-
-  # Verify npm is enabled in the container
-  test_scl_usage "npm --version" "2.15.1" "${cid_file}"
-
+test_web_app_http() {
   test_http "/" "Hello world"
   check_result $?
   test_http "/TextFile.txt" "A text file."
   check_result $?
-
-  test_pid_1 "${cid_file}"
-  check_result $?
-
-  cleanup_app
 }
 
-test_openshift_sample_app() {
-  local cid_file=$(mktemp -u --suffix=.cid)
+test_web_app_scl() {
+  local image="$1"
+  local cid_file="$2"
+
+  test_scl_usage "dotnet --version" "${dotnet_version}" "${cid_file}" "${image}"
+  check_result $?
+
+  # Verify $HOME != $CWD. See https://github.com/redhat-developer/s2i-dotnetcore/issues/28
+  test_scl_usage "pwd" "/opt/app-root/src" "${cid_file}" "${image}"
+  check_result $?
+  test_scl_usage "echo \$HOME" "/opt/app-root" "${cid_file}" "${image}"
+  check_result $?
+
+  # Verify npm is enabled in the container
+  test_scl_usage "npm --version" "2.15.1" "${cid_file}" "${image}"
+}
+
+init_web_app() {
+  local image="$1"
+  local cid_file="$2"
+
   # Verify that the HTTP connection can be established to test application container
-  run_test_application &
+  run_test_application "${image}" "${cid_file}" &
 
   # Wait for the container to write it's CID file
   wait_for_cid
 
-  test_scl_usage "dotnet --version" "${dotnet_version}" "${cid_file}"
+  test_pid_1 "${cid_file}"
+  check_result $?
+}
+
+test_web_application() {
+  local app="$1"
+  info "Starting web application tests for '${app}'"
+  prepare ${app}
+  run_s2i_build ${app}
+  check_result $?
+  create_runtime_app
+
+  build_image="${IMAGE_NAME}-testapp"
+  runtime_image="${RUNTIME_IMAGE_NAME}-testapp"
+
+  ##
+  # test the build container
+  ##
+  info "Starting build image tests"
+  local cid_file=$(mktemp -u --suffix=.cid)
+  init_web_app "${build_image}" "${cid_file}"
+  # test application with default user
+  test_web_app_scl "${build_image}" "${cid_file}"
+  test_web_app_http
+
+  # test application with random user
+  CONTAINER_ARGS="-u 12345" test_web_app_scl "${build_image}" "${cid_file}"
+  CONTAINER_ARGS="-u 12345" test_web_app_http
+  cleanup_container "${cid_file}"
+
+  ##
+  # test the runtime container
+  ##
+  info "Starting runtime image tests"
+  local cid_file=$(mktemp -u --suffix=.cid)
+  init_web_app "${runtime_image}" "${cid_file}"
+  # test application with default user
+  test_web_app_http
+
+  # test application with random user
+  CONTAINER_ARGS="-u 12345" test_web_app_http
+  cleanup_container "${cid_file}"
+
+  info "All web application tests for '${app}' finished successfully."
+  cleanup ${app}
+}
+
+test_openshift_sample_app() {
+  local image="$1"
+  local cid_file=$(mktemp -u --suffix=.cid)
+  # Verify that the HTTP connection can be established to test application container
+  run_test_application "${image}" "${cid_file}" &
+
+  # Wait for the container to write it's CID file
+  wait_for_cid
+
+  test_scl_usage "dotnet --version" "${dotnet_version}" "${cid_file}" "${image}"
   check_result $?
 
   test_http "/" "Sample pages using ASP.NET Core MVC" "grep \"ASP.NET Core MVC\" | sed -e 's#<li>##g' -e 's#</li>##g' -e 's#^ \\+##g'"
   check_result $?
 
-  cleanup_app
+  cleanup_container "${cid_file}"
 }
 
 echo_details() {
@@ -393,22 +455,35 @@ success_cli() {
 
 test_cli_app() {
   local app="$1"
-  info "Testing CLI app: ${app} ..."
+  info "Testing CLI app against build image: ${app} ..."
   prepare ${app}
   run_s2i_build ${app}
   check_result $?
 
   local expected="$( get_expected_cli ${app} )"
-  local actual_pre="$( run_cli_test_application )"
+  local actual_pre="$( run_cli_test_application ${IMAGE_NAME}-testapp)"
   local actual="$( filter_cli "${app}" "${actual_pre}" )"
   if ! success_cli "${app}" "${actual}" "${expected}"; then
     info "Test CLI app: ${app} FAILED."
     echo_details "${expected}" "${actual}"
     cleanup ${app}
     exit 1
-  else
-    info "Test CLI app: ${app} PASSED."
   fi
+  info "Test CLI app (build image): ${app} PASSED."
+
+  info "Testing CLI app against runtime image: ${app} ..."
+  create_runtime_app
+  #check_result $?
+  local expected="$( get_expected_cli ${app} )"
+  local actual_pre="$( run_cli_test_application ${RUNTIME_IMAGE_NAME}-testapp)"
+  local actual="$( filter_cli "${app}" "${actual_pre}" )"
+  if ! success_cli "${app}" "${actual}" "${expected}"; then
+    info "Test CLI app: ${app} FAILED."
+    echo_details "${expected}" "${actual}"
+    cleanup ${app}
+    exit 1
+  fi
+  info "Test CLI app (runtime image): ${app} PASSED."
   cleanup ${app}
 }
 
@@ -419,7 +494,7 @@ test_new_web_app() {
   check_result $?
 
   local cid_file=$(mktemp -u --suffix=.cid)
-  run_test_application &
+  run_test_application "${IMAGE_NAME}-testapp" "${cid_file}" &
   wait_for_cid
 
   # installed via DOTNET_NPM_TOOLS
@@ -429,9 +504,37 @@ test_new_web_app() {
   test_http "/js/site.min.js"
   check_result $?
 
-  cleanup_app
+  cleanup_container "${cid_file}"
   info "All tests for the ${app} finished successfully."
   cleanup ${app}
+}
+
+create_runtime_app() {
+  # Create a temp directory to hold our temporary files
+  TMPDIR=$(mktemp -d)
+  # TODO: Figure out a better way to allow access from the image /OTHER/ than 777
+  chmod 777 ${TMPDIR}
+  echo "Created temp directory ${TMPDIR}"
+  # Grab the build artifacts from the build image
+  docker run --rm --volume=${TMPDIR}:/opt/app-root/tmp:Z "${IMAGE_NAME}-testapp" tar zcvpf /opt/app-root/tmp/publish.tar.gz -C /opt/app-root/publish .
+
+  if [ ! -e "${TMPDIR}/publish.tar.gz" ] || [ ! -s "${TMPDIR}/publish.tar.gz" ]; then
+    echo "Failed to extract the publish directory from the build image '${app}'."
+    cleanup
+    exit 1
+  fi
+  echo "FROM ${RUNTIME_IMAGE_NAME}" > "${TMPDIR}/Dockerfile"
+  echo "RUN mkdir -p '/opt/app-root/publish'" >> "${TMPDIR}/Dockerfile"
+  echo "WORKDIR /opt/app-root/publish" >> "${TMPDIR}/Dockerfile"
+  echo "COPY publish.tar.gz publish.tar.gz" >> "${TMPDIR}/Dockerfile"
+  echo "RUN tar xvf publish.tar.gz" >> "${TMPDIR}/Dockerfile"
+  echo "CMD /opt/app-root/publish/s2i_run" >> "${TMPDIR}/Dockerfile"
+  # Build the runtime image
+  docker build -f "${TMPDIR}/Dockerfile" -t "${RUNTIME_IMAGE_NAME}-testapp" ${TMPDIR}
+  if [ -n ${TMPDIR} ] && [ -e ${TMPDIR} ]; then
+    echo "Removing temp directory ${TMPDIR}"
+    rm -rf ${TMPDIR}
+  fi
 }
 
 info "Testing ${IMAGE_NAME}"
@@ -456,10 +559,10 @@ if [ ${OPENSHIFT_ONLY} = true ]; then
   check_result $?
 
   # test application with default user
-  test_openshift_sample_app
+  test_openshift_sample_app "${IMAGE_NAME}-testapp"
 
   # test application with random user
-  CONTAINER_ARGS="-u 12345" test_openshift_sample_app
+  CONTAINER_ARGS="-u 12345" test_openshift_sample_app "${IMAGE_NAME}-testapp"
 
   info "All tests for the ${sample_app_url} finished successfully."
   cleanup "ignore-me"
@@ -471,18 +574,7 @@ else
   done
 
   for app in ${WEB_APPS[@]}; do
-    prepare ${app}
-    run_s2i_build ${app}
-    check_result $?
-
-    # test application with default user
-    test_web_application
-
-    # test application with random user
-    CONTAINER_ARGS="-u 12345" test_web_application
-
-    info "All tests for the ${app} finished successfully."
-    cleanup ${app}
+    test_web_application "${app}"
   done
 
   test_new_web_app
